# Generated by Django 3.2.8 on 2021-11-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_management', '0002_auto_20211117_0757'),
    ]

    operations = [
        migrations.CreateModel(
            name='Executionflg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mornig_flg', models.IntegerField(default=0)),
                ('last_time_flg', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='todo',
            name='flg',
            field=models.IntegerField(default=0),
        ),
    ]
