# Generated by Django 3.2.8 on 2021-11-20 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('self_management', '0003_auto_20211119_2043'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Executionflg',
        ),
    ]
