# Generated by Django 3.2.8 on 2021-11-20 13:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('self_management', '0004_delete_executionflg'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakfast',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cleaning',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='condition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sleep',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='breakfast',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cleaning',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='condition',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='diary',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateField(),
        ),
    ]
